### ISSUE TITLE
Change context to page with parital url match

### ISSUE THREAD

**Issue by Naimadnap** [TheSoftwareHouse/Kakunin#104]
Hi,

how to set the context to the current page with dynamic URL parameters.

### Scenario:
In my service, I'm able to add articles. Each article have own url part in order `<host>/articles/<article_id>`. When in test I use step `And the "<string>" page is displayed` I get error connected with URL matching.
Also in `node_modules/kakunin/dist/pages/base.js` I have added lines
```
console.log(_this.url)
console.log(currentUrl)
```
and get in console
```
/article
http://localhost:4100/article/pr-o2aqze
```
and error
```
And the "ArticlePreview" page is displayed # node_modules/kakunin/dist/step_definitions/navigation.js:22
TimeoutError: Wait timed out after 5005ms
at ...node_modules/selenium-webdriver/lib/promise.js:2201:17
at ManagedPromise.invokeCallback_ (...node_modules/selenium-webdriver/lib/promise.js:1376:14)
at TaskQueue.execute_ (...node_modules/selenium-webdriver/lib/promise.js:3084:14)
at TaskQueue.executeNext_ (...node_modules/selenium-webdriver/lib/promise.js:3067:27)
at asyncRun (...node_modules/selenium-webdriver/lib/promise.js:2927:27)
at ...node_modules/selenium-webdriver/lib/promise.js:668:7
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From: Task: <anonymous wait>
at scheduleWait (...node_modules/selenium-webdriver/lib/promise.js:2188:20)
at ControlFlow.wait (...node_modules/selenium-webdriver/lib/promise.js:2517:12)
at thenableWebDriverProxy.wait (...node_modules/selenium-webdriver/lib/webdriver.js:934:29)
at run (...node_modules/protractor/built/browser.js:59:33)
at ProtractorBrowser.to.(anonymous function) [as wait] (...node_modules/protractor/built/browser.js:67:16)
at ...node_modules/kakunin/dist/pages/base.js:52:22
at Generator.next (<anonymous>)
at step (...node_modules/kakunin/dist/pages/base.js:17:191)
at ...node_modules/kakunin/dist/pages/base.js:17:437
at new Promise (<anonymous>)
at ...node_modules/kakunin/dist/pages/base.js:17:99
at ArticlePreview.isOn (...node_modules/kakunin/dist/pages/base.js:60:7)
at World.<anonymous> (...node_modules/kakunin/dist/step_definitions/navigation.js:25:35)
```
and the ArticlePreview class
```
'use strict';
const { BasePage } = require('kakunin');
class ArticlePreview extends BasePage {
    constructor() {
        super();
        this.url = "/article";
        this.Title = $('h1');
        this.Description = $('#root > div > div > div.container.page > div.row.article-content > div > div > p')
    }
}
module.exports = ArticlePreview;
```

### Expected behaviour:
New step with partial match or better implementation of current steps

**Comment by simonsipl** [comment]
Hello @Naimadnap 
As I can see your ArticlePreviev class URL is `/article` in case of editing I assume your going into different URL like `/articles/<article_id>` which means your on different page object, so in this case you have to create new page object which will extend Class `ArticlePreview` and contain different URL
 To handle dynamic URLs id you can use: `/articles/:id` for the new page object

**Comment by simonsipl** [comment]
```
const { ArticlesPreview } = require('articlesPreview.js');
class Articles extends ArticlesPreview {
    constructor() {
        super();
        this.url = "/articles/:id";
    }
}
module.exports = Articles;
```

**Comment by Naimadnap** [comment]
thanks @simonsipl it works. Could you show me where it is in documentation or maybe it's a good case to write it down somewhere

**Comment by simonsipl** [comment]
A similar case is described in `I visit the ":pageFileName" page with parameters:` step definition, but if it's misleading I think we should add this to description @tgorskievo @sethii

**Comment by Naimadnap** [comment]
thanks
