### ISSUE TITLE
Kakunin failing to run, exits with `code: 100`

### ISSUE THREAD

**Issue by bobdenotter** [TheSoftwareHouse/Kakunin#188]
Hi, 

Recently kakunin in [our project](https://github.com/bolt/four) stopped working, and I'm not sure why.. Perhaps it's MacOS acting up, perhaps not. 

This is the error i'm getting: 

```
$ make e2e
make server
bin/console server:start 127.0.0.1:8088 -q || true
cd tests/e2e && npm run kakunin && cd ../..

> e2e@ kakunin /Users/bob/Sites/bolt-four/tests/e2e
> cross-env NODE_ENV=prod kakunin

All reports have been deleted!
[15:43:50] I/launcher - Running 1 instances of WebDriver
[15:43:50] I/local - Starting selenium standalone server...
[15:43:50] E/launcher - Error: Error: Server terminated early with status 1
    at /Users/bob/Sites/bolt-four/tests/e2e/node_modules/selenium-webdriver/remote/index.js:252:52
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
[15:43:50] E/launcher - Process exited with error code 100
Protractor has finished
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! e2e@ kakunin: `cross-env NODE_ENV=prod kakunin`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the e2e@ kakunin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bob/.npm/_logs/2019-07-08T13_43_50_890Z-debug.log
make: *** [e2e] Error 100
```

deubug.log is: 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'kakunin'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.5.0
4 verbose run-script [ 'prekakunin', 'kakunin', 'postkakunin' ]
5 info lifecycle e2e@~prekakunin: e2e@
6 info lifecycle e2e@~kakunin: e2e@
7 verbose lifecycle e2e@~kakunin: unsafe-perm in lifecycle true
8 verbose lifecycle e2e@~kakunin: PATH: [snip]
9 verbose lifecycle e2e@~kakunin: CWD: /Users/bob/Sites/bolt-four/tests/e2e
10 silly lifecycle e2e@~kakunin: Args: [ '-c', 'cross-env NODE_ENV=prod kakunin' ]
11 silly lifecycle e2e@~kakunin: Returned: code: 100  signal: null
12 info lifecycle e2e@~kakunin: Failed to exec kakunin script
13 verbose stack Error: e2e@ kakunin: `cross-env NODE_ENV=prod kakunin`
13 verbose stack Exit status 100
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid e2e@
15 verbose cwd /Users/bob/Sites/bolt-four/tests/e2e
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/Cellar/node/12.5.0/bin/node" "/usr/local/bin/npm" "run" "kakunin"
18 verbose node v12.5.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 100
22 error e2e@ kakunin: `cross-env NODE_ENV=prod kakunin`
22 error Exit status 100
23 error Failed at the e2e@ kakunin script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 100, true ]
```

Current versions: 

```
$ npm -v 
6.9.0
$ node -v  
v12.5.0
```

Package.json has this: 

```
{
  "name": "e2e",
  "description": "Bolt E2E tests",
  "private": true,
  "scripts": {
    "kakunin": "cross-env NODE_ENV=prod kakunin"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "kakunin": "^3.0",
    "protractor": "^5.4.2",
    "webdriver-manager": "^13.0.0"
  }
}
```

(i've tried upgrading from Kakunin 2.6 to 3.0, but that didn't make a difference in this case)

Any idea what might cause this?

**Comment by tgorskievo** [comment]
Hey @bobdenotter,

Since the 3.0.0 version, you don't have to add `protractor` and `webdriver` to the dependencies in package.json

1. Try to make the following steps on LTS version of node `v10.16.0`
2. Try to update Kakunin in your project to version `3.0.1`
You can find all migration notes under the following link:
- https://github.com/TheSoftwareHouse/Kakunin/blob/master/MIGRATION-3.0.0.MD
3. Make sure that you installed everything from scratch, so remove `package-lock`, `node_modules` and then make `npm install`

Please let me know if it helped, if not then we'll try to find another solution.

**Comment by bobdenotter** [comment]
Hi @tgorskievo, 

Thank you! My package.json is now slimmed down to this: 

```
{
  "name": "e2e",
  "description": "Bolt E2E tests",
  "private": true,
  "scripts": {
    "kakunin": "cross-env NODE_ENV=prod kakunin"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "kakunin": "^3.0"
  }
}
```

After that, rebuilding node_modules helped. Looks like I need to update a few tests, but I think i'll manage. Thanks so far! 👍

**Comment by tgorskievo** [comment]
Hey @bobdenotter 

Great, you're welcome! Feel free to ask questions if you face any problems, we're here to help
