### ISSUE TITLE
Tests are terminated if alert box opens

### ISSUE THREAD

**Issue by simonsipl** [TheSoftwareHouse/Kakunin#32]
Tests are terminated if alert box opens, there should be mechanism to ignore, accept or dismiss alertbox in config.

```
-.[15:30:42] E/launcher - unexpected alert open: {Alert text : }
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.12.6 x86_64)
[15:30:42] E/launcher - UnexpectedAlertOpenError: unexpected alert open: {Alert text : }
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.12.6 x86_64)
    at Object.checkLegacyResponse (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:553:13)
    at parseHttpResponse (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From: Task: WebDriver.manage().deleteAllCookies()
    at thenableWebDriverProxy.schedule (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Options.deleteAllCookies (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1263:25)
    at cookiesFunc (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/kakunin/dist/configuration/hooks.js:58:53)
    at clearCookiesAndLocalStorage (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/kakunin/dist/configuration/hooks.js:66:3)
    at takeScreenshot.then (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/kakunin/dist/configuration/hooks.js:90:9)
    at ManagedPromise.invokeCallback_ (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/hikaryu/TSH_Projects/*/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/hikaryu/TSH_Projects/BrickVest/e2e-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[15:30:42] E/launcher - Process exited with error code 199

```

**Comment by sethii** [comment]
Fixed in 2.1
